### ISSUE TITLE
Interpolate spaces between datapoints

### ISSUE THREAD

**Issue by unfa** [x42/spectra.lv2#2]
Right now Spectra displays vertical lines as frequencies, however there's lots of empty space between the data points (especially on low frequencies). I quess it'd be good to have some interpolation in place to fill in the gaps, so the user sees a line graph, rather than a lollipop graph (as that's what it is right now).

![image](https://user-images.githubusercontent.com/491704/51767411-8f90bf00-20dd-11e9-8ef1-10700773bbdf.png)
(please excuse the terrible screen tearing - Shutter does that)

**Comment by x42** [comment]
This is exactly what distinguishes this analyzer from others: The vertical line does track a given frequency's phase and matches the precise frequency (not the whole band).

if you want broad interpolation, this analyzer is not for you. This is more of a technical, not musical, tool. e.g it helped recently to match tube models to actual analog hardware  https://imgur.com/a/toaHykr

Looking at your spectrum you probably want a perceptual analyzer like the one built into x42-eq.

**Comment by unfa** [comment]
Interesting! Thanks for the explanation!

**Comment by x42** [comment]
For upcoming documentation, here's an animated gif that shows the difference.

Note that you can read the exact peak frequency from spectra. The vertical line is correct even at low frequencies, while other analyzers just show some spread-out block for the FFT-bin.

![spectr](https://user-images.githubusercontent.com/30246/52827643-f9d9c580-30c5-11e9-9618-c1808f22bfb8.gif)

**Comment by unfa** [comment]
Oh wow! I didn't know it was *that* accurate!
It's pretty amazing.
